### ISSUE TITLE
Not enough sass

### ISSUE THREAD

**Issue by jasper-lu** [stevezhu/meteor-sass#5]
Come on steve, this is noob level sass. You need more sassy in your code.

Some suggestions for this would be to change your variable names.

For example, you could change your variable name in line 77 of compile-sass.js, so that instead of reading

    result = future.wait();

it reads

    noImNotGonnaWait = future.wait();

or change line 33 from 

    var optionsSource = fs.readFileSync(optionsFilePath);

to 

    var readingIsForTheWeak = fs.readFileSync(optionsFilePath);

Can't wait to see these changes in version 2.1.

**Comment by stevezhu** [comment]
HAHAHAH

**Comment by stevezhu** [comment]
Not gonna lie, I'm very tempted.

**Comment by jasper-lu** [comment]
What would you do without me
