### ISSUE TITLE
Errors while adding packages for ionic and ionicons

### ISSUE THREAD

**Issue by mervynteo** [stevezhu/meteor-sass#7]
When I run both meteor add for both meteoric:ionic-sass and meteoric:ionicons.-sass, it shows the error below.

=> Errors while adding packages:

While checking for stevezhu:sass@1.3.7:
error: No compatible binary build found for this package. Contact the
package author and ask them to publish it for your platform.

I use a windows machine btw...is that the problem?

**Comment by stevezhu** [comment]
Hey sorry for the extremely late response; I haven't really been programming in the past few months. Hopefully you figured out to use fourseven:scss which I believe both of those packages are meant to be used with.

**Comment by mervynteo** [comment]
Hi Steve,

Not to worry, I managed to get it working by using a Macbook instead of a
Windows.
Hope you can get back soon!

Keep in touch :)
Mervyn Teo
